# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 15:56
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_auto_20150611_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download_file',
            name='platform',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='download.Platform'),
        ),
    ]
